<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210329215726 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client CHANGE NOM NOM VARCHAR(255) DEFAULT NULL, CHANGE PRENOM PRENOM VARCHAR(255) DEFAULT NULL, CHANGE ADR ADR VARCHAR(255) DEFAULT NULL, CHANGE VILLE VILLE VARCHAR(255) DEFAULT NULL, CHANGE CP CP INT DEFAULT NULL, CHANGE TEL TEL BIGINT DEFAULT NULL, CHANGE MAIL MAIL VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnostic CHANGE PRIX PRIX BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE evenement CHANGE MOYEN MOYEN VARCHAR(255) DEFAULT NULL, CHANGE DEMANDE DEMANDE VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE intervenir CHANGE DESCRIPTION DESCRIPTION VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX I_FK_MATERIEL_PANNE ON materiel');
        $this->addSql('ALTER TABLE materiel ADD panne_id BIGINT NOT NULL, DROP PANNE, CHANGE TYPE TYPE VARCHAR(255) DEFAULT NULL, CHANGE MARQUE MARQUE VARCHAR(255) DEFAULT NULL, CHANGE MODEL MODEL VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_18D2B09165B7B5BD ON materiel (panne_id)');
        $this->addSql('ALTER TABLE paiement CHANGE MONTANT MONTANT BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE panne CHANGE PIECE PIECE INT NOT NULL, CHANGE DESCRIPTION DESCRIPTION VARCHAR(255) DEFAULT NULL, CHANGE ETAT ETAT VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE piece CHANGE LIBELLE LIBELLE VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE reparation CHANGE ESTIMATION ESTIMATION BIGINT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client CHANGE NOM NOM VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE PRENOM PRENOM VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE ADR ADR VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE VILLE VILLE VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE CP CP INT NOT NULL, CHANGE TEL TEL BIGINT NOT NULL, CHANGE MAIL MAIL VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`');
        $this->addSql('ALTER TABLE diagnostic CHANGE PRIX PRIX BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E03737BCC3D3');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E037DEE12CDD');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E03777EFE652');
        $this->addSql('ALTER TABLE dossier CHANGE NUM NUM INT NOT NULL, CHANGE STATUT STATUT VARCHAR(255) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, CHANGE DATE_DOSSIER DATE_DOSSIER DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE ESTIMATION ESTIMATION BIGINT DEFAULT NULL, CHANGE DEVIS DEVIS BIGINT DEFAULT NULL, CHANGE CLIENT CLIENT BIGINT DEFAULT NULL, CHANGE PAIEMENT PAIEMENT BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE evenement CHANGE MOYEN MOYEN VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`, CHANGE DEMANDE DEMANDE VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`');
        $this->addSql('ALTER TABLE intervenir CHANGE DESCRIPTION DESCRIPTION VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`');
        $this->addSql('ALTER TABLE materiel DROP FOREIGN KEY FK_18D2B09165B7B5BD');
        $this->addSql('DROP INDEX IDX_18D2B09165B7B5BD ON materiel');
        $this->addSql('ALTER TABLE materiel ADD PANNE INT NOT NULL, DROP panne_id, CHANGE TYPE TYPE VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`, CHANGE MARQUE MARQUE VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`, CHANGE MODEL MODEL VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`');
        $this->addSql('CREATE INDEX I_FK_MATERIEL_PANNE ON materiel (PANNE)');
        $this->addSql('ALTER TABLE paiement CHANGE MONTANT MONTANT BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE panne DROP FOREIGN KEY FK_3885B260B39EC993');
        $this->addSql('ALTER TABLE panne CHANGE DESCRIPTION DESCRIPTION VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`, CHANGE ETAT ETAT VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`, CHANGE PIECE PIECE BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE piece CHANGE LIBELLE LIBELLE VARCHAR(255) CHARACTER SET latin1 DEFAULT \'NULL\' COLLATE `latin1_swedish_ci`');
        $this->addSql('ALTER TABLE reparation CHANGE ESTIMATION ESTIMATION BIGINT DEFAULT NULL');
    }
}
